[package]
name = "goldprice"
version = "2.2.28"
description = "Gold price desktop client"
authors = ["Lucas"]
license = "MIT"
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }
cc = "1.0"

[dependencies]
tauri = { version = "1.5", features = [ "devtools", "dialog-all", "http-all", "system-tray", "window-all", "fs-all", "path-all", "shell-open"] }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
auto-launch = "0.5"
window-shadows = "0.2"
reqwest = { version = "0.11", default-features = false, features = ["native-tls", "cookies", "stream"] }
futures-util = "0.3"
tokio = { version = "1", features = ["time"] }
tokio-tungstenite = { version = "0.21", default-features = false, features = ["connect", "native-tls"] }
time = { version = "0.3", features = ["formatting"] }
uuid = { version = "1", features = ["v4"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "z"
strip = true
